/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package example.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum EventType {
  meeting  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EventType\",\"namespace\":\"example.avro\",\"symbols\":[\"meeting\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
