/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.apache.flink.streaming.tests.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class InnerPayLoadAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7835393938967091001L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"InnerPayLoadAvro\",\"namespace\":\"org.apache.flink.streaming.tests.avro\",\"fields\":[{\"name\":\"sequenceNumber\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<InnerPayLoadAvro> ENCODER =
      new BinaryMessageEncoder<InnerPayLoadAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<InnerPayLoadAvro> DECODER =
      new BinaryMessageDecoder<InnerPayLoadAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<InnerPayLoadAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<InnerPayLoadAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<InnerPayLoadAvro>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this InnerPayLoadAvro to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a InnerPayLoadAvro from a ByteBuffer. */
  public static InnerPayLoadAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long sequenceNumber;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public InnerPayLoadAvro() {}

  /**
   * All-args constructor.
   * @param sequenceNumber The new value for sequenceNumber
   */
  public InnerPayLoadAvro(java.lang.Long sequenceNumber) {
    this.sequenceNumber = sequenceNumber;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sequenceNumber;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sequenceNumber = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'sequenceNumber' field.
   * @return The value of the 'sequenceNumber' field.
   */
  public java.lang.Long getSequenceNumber() {
    return sequenceNumber;
  }

  /**
   * Sets the value of the 'sequenceNumber' field.
   * @param value the value to set.
   */
  public void setSequenceNumber(java.lang.Long value) {
    this.sequenceNumber = value;
  }

  /**
   * Creates a new InnerPayLoadAvro RecordBuilder.
   * @return A new InnerPayLoadAvro RecordBuilder
   */
  public static org.apache.flink.streaming.tests.avro.InnerPayLoadAvro.Builder newBuilder() {
    return new org.apache.flink.streaming.tests.avro.InnerPayLoadAvro.Builder();
  }

  /**
   * Creates a new InnerPayLoadAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new InnerPayLoadAvro RecordBuilder
   */
  public static org.apache.flink.streaming.tests.avro.InnerPayLoadAvro.Builder newBuilder(org.apache.flink.streaming.tests.avro.InnerPayLoadAvro.Builder other) {
    return new org.apache.flink.streaming.tests.avro.InnerPayLoadAvro.Builder(other);
  }

  /**
   * Creates a new InnerPayLoadAvro RecordBuilder by copying an existing InnerPayLoadAvro instance.
   * @param other The existing instance to copy.
   * @return A new InnerPayLoadAvro RecordBuilder
   */
  public static org.apache.flink.streaming.tests.avro.InnerPayLoadAvro.Builder newBuilder(org.apache.flink.streaming.tests.avro.InnerPayLoadAvro other) {
    return new org.apache.flink.streaming.tests.avro.InnerPayLoadAvro.Builder(other);
  }

  /**
   * RecordBuilder for InnerPayLoadAvro instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<InnerPayLoadAvro>
    implements org.apache.avro.data.RecordBuilder<InnerPayLoadAvro> {

    private long sequenceNumber;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.apache.flink.streaming.tests.avro.InnerPayLoadAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sequenceNumber)) {
        this.sequenceNumber = data().deepCopy(fields()[0].schema(), other.sequenceNumber);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing InnerPayLoadAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(org.apache.flink.streaming.tests.avro.InnerPayLoadAvro other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.sequenceNumber)) {
        this.sequenceNumber = data().deepCopy(fields()[0].schema(), other.sequenceNumber);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'sequenceNumber' field.
      * @return The value.
      */
    public java.lang.Long getSequenceNumber() {
      return sequenceNumber;
    }

    /**
      * Sets the value of the 'sequenceNumber' field.
      * @param value The value of 'sequenceNumber'.
      * @return This builder.
      */
    public org.apache.flink.streaming.tests.avro.InnerPayLoadAvro.Builder setSequenceNumber(long value) {
      validate(fields()[0], value);
      this.sequenceNumber = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sequenceNumber' field has been set.
      * @return True if the 'sequenceNumber' field has been set, false otherwise.
      */
    public boolean hasSequenceNumber() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sequenceNumber' field.
      * @return This builder.
      */
    public org.apache.flink.streaming.tests.avro.InnerPayLoadAvro.Builder clearSequenceNumber() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public InnerPayLoadAvro build() {
      try {
        InnerPayLoadAvro record = new InnerPayLoadAvro();
        record.sequenceNumber = fieldSetFlags()[0] ? this.sequenceNumber : (java.lang.Long) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<InnerPayLoadAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<InnerPayLoadAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<InnerPayLoadAvro>
    READER$ = (org.apache.avro.io.DatumReader<InnerPayLoadAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
